---

- name: apt
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: google apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D38B4796

  - name: google apt repo
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

  - name: microsoft apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: BE1229CF

  - name: microsoft apt repo
    apt_repository:
      repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main

  - name: apt update
    apt:
      update_cache: yes

  - name: install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - git
        - papirus-icon-theme
        - fonts-inconsolata
        - google-chrome-stable
        - code
        - yakuake

  - name: remove apport
    apt:
      name: apport
      state: absent
      purge: yes

  - name: autoremove
    apt:
      autoremove: yes
