---

- name: base
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: google apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D38B4796

  - name: google apt repo
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      filename: google-chrome

  - name: install apt packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - git
        - papirus-icon-theme
        - google-chrome-stable

  - name: install snap packages
    snap:
      name: "{{ packages }}"
    vars:
      packages:
        - htop
        - jq

  - name: remove apport
    apt:
      name: apport
      state: absent
      purge: yes

  - name: copy dotfiles
    copy:
      src: bash/
      dest: /home/davido/

  - name: autoremove
    apt:
      autoremove: yes
