---

- name: base (root)
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: google apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D38B4796

  - name: google apt repo
    apt_repository:
      repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
      filename: google-chrome

  - name: install apt packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - vim
        - git
        - papirus-icon-theme
        - google-chrome-stable
        - htop
        - jq
        - curl
        - fish
        - fonts-hack
        - fonts-noto-color-emoji

  - name: remove apport and switcheroo
    apt:
      name: "{{ packages }}"
      state: absent
      purge: yes
    vars:
      packages:
        - apport
        - switcheroo-control

  - name: autoremove
    apt:
      autoremove: yes


- name: base
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:

  - name: disable animations
    dconf:
      key: /org/gnome/desktop/interface/enable-animations
      value: 'false'

  - name: dock autohide
    dconf:
      key: /org/gnome/shell/extensions/dash-to-dock/dock-fixed
      value: 'false'

  - name: hide home icon
    dconf:
      key: /org/gnome/shell/extensions/desktop-icons/show-home
      value: 'false'

  - name: hide trash icon
    dconf:
      key: /org/gnome/shell/extensions/desktop-icons/show-trash
      value: 'false'

  - name: default monospace font
    dconf:
      key: /org/gnome/desktop/interface/monospace-font-name
      value: "'Hack 11'"
