---

- name: docker
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: ensure docker group exists
    group:
      name: docker

  - name: add my user to docker group
    user:
      name: davido
      groups: docker
      append: yes

  - name: install docker
    snap:
      name: docker
      channel: stable
