---

- name: fonts
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:

  - name: install fonts
    copy:
      src: fonts/
      dest: /home/davido/.fonts/

  - name: run fc_cache
    command: fc-cache -r
