---

- name: pyenv apt
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: install packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - make
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - wget
        - curl
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libffi-dev
        - liblzma-dev
        - python-openssl

- name: pyenv
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:

  - name: install pyenv
    shell: curl https://pyenv.run | bash
    args:
      executable: /bin/bash
