---

- name: syncthing
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: install syncthing
    snap:
      name: syncthing
      channel: stable

- name: syncthing user
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:

  - name: user systemd folder
    file:
      path: /home/davido/.config/systemd/user
      state: directory

  - name: copy unit file
    copy:
      src: syncthing/syncthing.service
      dest: /home/davido/.config/systemd/user/syncthing.service

  - name: syncthing service
    systemd:
      name: syncthing
      scope: user
      enabled: yes
      state: started
