---

- name: vscodium
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: vscodium apt key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 54678CF75A278D9C

  - name: vscodium apt repo
    apt_repository:
      repo: deb https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main
      filename: vscodium

  - name: install vscodium
    apt:
      name: codium

- name: vscodium settings
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: davido
  tasks:

  - name: install vscodium settings
    copy:
      src: vscodium/
      dest: /home/davido/.config/VSCodium/User/
